language: java
branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
addons:
  sonarqube: 
    token:
      secure: PQ+aNz7lsoUvSgMDMWdsVB1RRgUObwrSWAnaoO3t/55iyC/axqPHVj4EKwEjoQayXZpTftNXspl2O2jxFTpU2C6476Y8mu8wH8o1QEQFvXb7R8LucK51kV15a99NgjrCx421MFekSa1p4joYyhHr6nKnRQdufy5v/Zm6C4SGVBqdN5EYBHQT8PX2kW1/7mYsdlad9IIBEgzuNf72KESp3Ff0d3Eiaaq6wmNmM8EYa+1oN+i2AbJ5ww5L4vWyBK4EXTS8Skb7kMptWkKj8O5h826H2MfVGvBODKSaTsCgywz0sTlDud5PO5Ykn8IZjGggU8qvohyHu02VHWCYzwn+BkBeaR66LaEq7hGMUmx2rkb9oD28P8hEe8Wrf3NiIpzQuxx/DG96XDcfR/nHt5YllOiesW+QCnqewo8NmydyqBwQF5GnBa5su+HQ18RdVBISsY35d8EUVHvxAs9a70NujAOZ+LkQdmhTDWqERODBmvc9hNJNdMdUdAyRmpB2QQqxKRmPttNjWjRq4Xae/r184dgXNa7fhpbHqUP3nUDvCDwB+PFPPu/7J7UlQGWlT72SOUTwOTmUjM8YkbxlIKkfjO2hhL09PC65+qEz/oR+S70bJKiNwt9fvUZ2YwqBTHEbCBe39D+n5BhuiDPoNbfqM78QgoCWcHADOhGiJrQ+PJ0=
    github_token:
      secure: c/iQKrg4DckDv7d0caioudoBFdkxaBHZpxmBTT0t9kyOaVkHBBWy3jcvrRkak9w1p+MosKmYLE8x3NmbOCC5snB2A6VUlbapjmA5PKh5cMML053dAcSefBaakkbP3egF5YbKu36uaKUMDktECAGrZ9iM4UYnpFnFGnviiW7d9DqhOcWGqBwK9QIiPNGq0eK4dLBP4W1XgFe2gudJ7xbyeezFDSORHOMPYpPcsyQrFov9P052Tc5Y0wnW+E9dXve3JxqXBgMfz8ByyrAQ4OhhcgyLl+KB1CKRZcAof7XIZaf3dl+M37Jym13kZvrzhyC1n5a8er5qLtl99ocoPHl1e4AHyGIt4d+EE7RzCt3x8KCbRdgqdYxmX6b8f+PlfWcxCYIwJe23bMVES6YeloKAW+XUvrWOdaRkGjg0bA8aI8WNRK12KJArbQ+LXHtdKLcR/MvWDyrBzIgKwq9X7yWl04yifXvZ+Ye6GuVINmyaEZN1YgrnLuY6/Vg0AB7ysqA1dc8oAOR2eE3PExHfz2po9aZoTzpxpPqwpcilzpLJfM2JL0ThDJ4k1Hu8WpO+LjhQ5V/2oR/hF7Mm8S+dYe1pLeuQkeWdOAcaPRJaTxtyRUksI2zz7y9hL+5mTubNpWVDU9HofY8BU8yeg1PkahdDIr3B7S2sgAPywT+bZvVHjc4=
jdk:
  - oraclejdk8
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
install:
  - mvn clean --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
#TODO To not forget to revert it back later, when travis sonar integration will be fixed. 
#script: 
#  - sonar-scanner 
deploy:
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      repo: sbtqa/page-factory
      branch: master
      jdk: oraclejdk8
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      repo: sbtqa/page-factory
      tags: true
      jdk: oraclejdk8
notifications:
  email: false
  slack:
    rooms:
      - secure: mFVdf0bKCOTqAIy+FZmMXUYPfJX0HrjZJ88kpM90aB/ihu+wIu49HoloSWiayXETl7A4h/21QBTXVDW0gRxqEhg9lKTpdWrNcOA/bG9vWN3xE4OcE3E7EVz1yL4dTWiMnKJkW+TcwKGhWv0z9hRin6A4jQANyJ88qd9MQNviO2yVIZBRGnqrXEVIYppwp7mb1jhwIdY6D1BJYudxRU+RZ9bYzumOkJ6ig+Qf2CNb0Cf1kho3Z+VM+Kg+qvOyPvnadZltlNbxfrUgEhd501uI4YVrSZXifPKNGeA7lRWHbtgnpV6HWQvFjINd8QKGcqBzY32PtB7ZSqNOMLkg2ombNk76fDln9M2BtAvDzNB2z9o+KdBnzzPHQ9qSUu7J3c24/74CIHtFSr1A//pnkSBlIZgMnOTsyqrI0tUY6+FtbKt0DuOjUXaYL3jOvHeFKFLPG3CTDOekTrbO3U1HPbMF/bIz9mfvMxgmdrbUtTCpSTRarB0KMI1+XWpxpAo1zz+sNVNlmD3Izx16jCerkw7Ogxuk3+Kf+kVkuZgn5giCxOrYD2aMqtIifA2Hh7N4Ox45CSD8395dzVG9Oty6I/VKadboHp8zorSYBhulju5VcTR+iRamwbAsEndvKUJHckzmtC0qnIXo0NxmgHycb4reoMajQyLZvrqB0a7FD/vnuJ8=
    on_success: change
    on_failure: always
    template:
      - "Build status: %{message}"
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"